task:
  name: FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-14-0-snap
      image_family: freebsd-13-2
      image_family: freebsd-12-3

  env:
    MAKE_FLAGS: -j 3

  pkginstall_script:
    - pkg install -y cmake git libowfat openssl
  compile_script:
    - echo -e "set(QSMTP_BUILD_DIR \"/tmp/Qs-build\")\nset(dashboard_model \"Continuous\")\nset(CONF_OPTIONS \"-DIPV4ONLY=On\")\nset(CTEST_SITE \"cirrus-ci.org\")\ninclude(\"$(pwd)/ctest_qsmtp.cmake\")" > my_qsmtp.cmake
    - ctest -V -D "CTEST_BUILD_NAME=FreeBSD $(uname -r)" -S my_qsmtp.cmake
