language: c
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MVb7IsCI3oSZS2Frwn2qQLpxjIWIOCFx8qsx1Mdh++7GWTQyikSOSnKV+ThFHK/QS8yLBQ76uwhyieoAPUmWtBBa7JBkuo52FUdkzhmX+hvKL5zaCzlP0LvmXdgU6rbnberrKRZyhLMVh+UKxF0cRlcSa21oQrnigx8wSJOjuyWGZ1OL1xeRqjmuroGt1KEy1VyUpquc3uTL4c/F2JXnaOHFX+RApJCP2uFZFvInBDyH5L/hRNax7kg49QyEi8E/8AmnfMOf+OYAROk7PvB9djXkfFwXpi7jXenAb0O/JO+JTkCNFZriXjQi5PgZ+y4H4/waHIbMlia+J4+FeoFvdda0iGurdE8D0/xZdITS0+0ubfaVUt3Z1tNAAL+Ont4Xru8LMq+sXz45QC0RhlzrIddvKU/97NdK/it/f2dQSpKl2j57u5j4Fnk4A1Tv7nSC1xx/6RPH9kYub4O2TfrM6PFWUxRBpn06rCJaTrP3GGuoBrkE2ezJDj4Lo8RqZXrSL/22taacwXx+yhNMQmEvLzVaKFR4Qlck6e6RhId9ktprn3/U9F5PrljkEjj2j3vb0PmKei3iFiJyw+UWRV02LP18tvqxv1gKBoI5QGkxQejGfeBHbb58oe0GqRY6FFyE+Dhkc3aarYrJB4dF4V9ssy+JbmvGlAp8LP3Uztoo/gk="
sudo: false
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - libowfat-dev
      - openssl
      - valgrind
  coverity_scan:
    project:
      name: "DerDakon/Qsmtp"
      description: "Build submitted via Travis CI"
    notification_email: eike@sf-mail.de
    build_command_prepend: "wget -O /tmp/cmake.tar --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz; tar xf /tmp/cmake.tar -C /tmp; export PATH=/tmp/cmake-3.4.3-Linux-x86_64/bin:/tmp/coverity-scan-analysis/cov-analysis-linux64-7.7.0.4/bin:${PATH}; mkdir covbuild; cd covbuild; cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_DOC=Off /home/travis/build/DerDakon/Qsmtp"
    build_command: "make -j 4"
    branch_pattern: coverity_scan
script:
 # install a working version from upstream, the Ubuntu version is too old
 - wget -O /tmp/cmake.tar -nc --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz || true
 - tar xf /tmp/cmake.tar -C /tmp
 - export PATH=/tmp/cmake-3.4.3-Linux-x86_64/bin:${PATH}
 - echo -e 'set(QSMTP_BUILD_DIR "/tmp/Qs-build")\nset(dashboard_model "Continuous")\nset(CONF_OPTIONS "-DIPV4ONLY=On")\nset(CTEST_SITE "travis-ci.org")\ninclude("/home/travis/build/DerDakon/Qsmtp/ctest_qsmtp.cmake")' > my_qsmtp.cmake
 - ctest -V -S my_qsmtp.cmake
