dist: bionic
language: c
version: ~> 1.0
jobs:
  include:
    - os: linux
      compiler: gcc
      arch: amd64
      env:
        - CTEST_BUILD_NAME="Ubuntu Bionic ${TRAVIS_ARCH} gcc"
    - os: linux
      compiler: clang
      arch: amd64
      env:
        - CTEST_BUILD_NAME="Ubuntu Bionic ${TRAVIS_ARCH} Clang"
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EGED1QtcBZ7U1WYBhNVuOlvvMcYsT+e/MMiE26ejEwysh7dGu3YxeKmOKs3+Pl+e31niwH6fqi9qXbQHb2A0hXsE3AzykzKJyVCgl5RmUR4J4ViamIdRHT8vGyoBLZvTia6s0PvlHRIfABvrjnloJ1t6yxO5JJNyMNz3uAnSDw1oaNTWCWiMA4TxVP9IxMHng/iF06mJa6pVsCgC/zVK40pKzs76sk4m+zX4vpvSdD9dPMzhhQbWSce/uyE9M8y39wDpgmXOMCIq+hrgCBaH+z5HQ7y37xw2a2VI0tCBmWEq84AKLG+t3D2F1L4wLwKAfrD6EfA9j/I3i2Md0y/DyrP9UpQkZjHAQX/9pFruXPxWyT9HS2Te0PD9iob5TXg41Ufl9E4oj316K9j9mPwdSttDiG5YqRc7nm0mPARFmGYWtQwwbRWdmq+2OmGNY8V7TtNq/jaOuFUXkLZ8xLBcvWSrx7kXPbNfp+rgL8B9Pz7V0Y/pQ2nLw1huRXE3JV8Zt5v7UF7Y7JPOrEPUiXBGCOP0CTH3D3QFovRiT9CiL8IR2xV19RCLje77tJlbmsZDnSZ6gIyby0h0mAKbin5ntA50fYcfJHWiorXjyZ53/0bOMqMGjnlAQS1+cctgTSQYbGuxoZ47O+AWXYEWV4Sec3lymstt/abFEa/lSjM3NoI="
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-2019.asc'
    packages:
      - cmake
      - libowfat-dev
      - libssl-dev
      - openssl
      - valgrind
      - libbsd-dev
  coverity_scan:
    project:
      name: "DerDakon/Qsmtp"
      description: "Build submitted via Travis CI"
    notification_email: eike@sf-mail.de
    build_command_prepend: "mkdir covbuild; cd covbuild; cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_DOC=Off ${TRAVIS_BUILD_DIR}"
    build_command: "make -j 4"
    branch_pattern: coverity_scan
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libowfat openssl; export OPENSSL_ROOT_DIR="/usr/local/opt/openssl"; fi
script:
 - echo -e 'set(QSMTP_BUILD_DIR "/tmp/Qs-build")\nset(dashboard_model "Continuous")\nset(CONF_OPTIONS "-DIPV4ONLY=On")\nset(CTEST_SITE "travis-ci.org")\ninclude("$ENV{TRAVIS_BUILD_DIR}/ctest_qsmtp.cmake")' > my_qsmtp.cmake
 - ctest -V -D "CTEST_BUILD_NAME=${CTEST_BUILD_NAME}" -S my_qsmtp.cmake
