INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(MUDFLAP_LIBRARY
		NAMES mudflap
)
MARK_AS_ADVANCED(MUDFLAP_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(mudflap DEFAULT_MSG MUDFLAP_LIBRARY)

IF(MUDFLAP_FOUND)
	SET(MUDFLAP_LIBRARIES ${MUDFLAP_LIBRARY})
ENDIF(MUDFLAP_FOUND)
