include(FindPackageHandleStandardArgs)

find_library(MUDFLAP_LIBRARY
		NAMES mudflap
)
mark_as_advanced(MUDFLAP_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(mudflap DEFAULT_MSG MUDFLAP_LIBRARY)

if(MUDFLAP_FOUND)
	set(MUDFLAP_LIBRARIES ${MUDFLAP_LIBRARY})
endif()
