INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(OWFAT_INCLUDE_DIR
		PATH_SUFFIXES libowfat
		PATHS /opt/diet/include
		NAMES taia.h
)
MARK_AS_ADVANCED(OWFAT_INCLUDE_DIR)

FIND_LIBRARY(OWFAT_LIBRARY
		NAMES owfat
		PATHS /opt/diet/lib
)
MARK_AS_ADVANCED(OWFAT_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(owfat DEFAULT_MSG OWFAT_LIBRARY OWFAT_INCLUDE_DIR)

IF(OWFAT_FOUND)
	SET(OWFAT_INCLUDE_DIRS ${OWFAT_INCLUDE_DIR})
	SET(OWFAT_LIBRARIES ${OWFAT_LIBRARY})
ENDIF(OWFAT_FOUND)
